#!/usr/bin/env bash

# configure your path directory
while true; do
	xsetroot -name "$($HOME/.config/status-dwm/wifi.sh) $($HOME/.config/status-dwm/temperature.sh)  $($HOME/.config/status-dwm/backlight.sh)  $($HOME/.config/status-dwm/memory.sh)  $($HOME/.config/status-dwm/volume.sh)  $(date +" %d.%m.%Y   %H:%M")  $($HOME/.config/status-dwm/bat-capacity.sh)$($HOME/.config/status-dwm/bat-state.sh)"
    sleep 1
done
