#!/usr/bin/env bash

# For dwmstatus
while true; do
	xsetroot -name " $($HOME/.config/dwm-status/memory.sh)  $($HOME/.config/dwm-status/filesystem.sh)  $($HOME/.config/dwm-status/backlight.sh)  $($HOME/.config/dwm-status/volume.sh)  $(date +" %H:%M   %A,%y/%m/%d")  $($HOME/.config/dwm-status/bat-capacity.sh)$($HOME/.config/dwm-status/bat-state.sh)   MASPENK"
    sleep 1
done
